### ISSUE TITLE
`quill-editor.component.d.ts` has an unknown import in distribution files on npmjs.com `import("parchment").Registry`

### ISSUE THREAD

**Issue by Halanson** [KillerCodeMonkey/ngx-quill#1895]
I updated ngx-quill to 26.0.5 and quill to 2.0.2 via npm in my Angular 18.1.1 app. During TS compilation I always getting this error:

```
✘ [ERROR] TS2694: Namespace '"/app/node_modules/parchment/dist/src/parchment"' has no exported member 'Registry'. [plugin angular-compiler]
     node_modules/ngx-quill/lib/quill-editor.component.d.ts:55:79:
       55 │ ...import("@angular/core").InputSignal<import("parchment").Registry>;
          ╵                                                            ~~~~~~~~
```
I checked the source code on my node_moduls and this line exists as expected. I also checked this repository https://github.com/KillerCodeMonkey/ngx-quill/blob/master/projects/ngx-quill/src/lib/quill-editor.component.ts#L99 and the zip file of version 26.0.5 release, but there is no import. Using the code tab of the npmjs.com registry, I find the line the compiler blames about. 

I searched npmjs.com for parchment. Looks like this is the document model for quilljs. According to my node_modeles folder, I have parchment installed but not required in my package.json.

I also did a clean install. Have I missed something? Thank you for your help!

**Comment by KillerCodeMonkey** [comment]
Maybe you have typings installed? But for quill v2 no extra typings should be installed

**Comment by Halanson** [comment]
I'm not really sure how I fixed this, but the issue is gone. I also removed the typings for quilljs but I also changed some type hints in my code. I guess the combination of both fixed the issue. 

Thank you for your help.

**Comment by sambalmueslie** [comment]
I had the same issue. I solved it by
* Removing the typings as recommended by @KillerCodeMonkey 
* Delete node_modules
* Delete package-lock.json
* Run ``npm i``

**Comment by ArturQuirino** [comment]
I'm facing the same problem, but the tricks that were describe did not solve my problem.

I'm still having problems, even not using typing and deleting node_modules and package-lock over and over.

**Comment by KillerCodeMonkey** [comment]
Did you checked out the Demo repo?

It is working there.

Maybe you have some old typings installed?

For quill 2.0 you do not need any additional typings to be installed. Even @types/quill v2 exist
