### ISSUE TITLE
Databinding not working 

### ISSUE THREAD

**Issue by TauanMatos** [KillerCodeMonkey/ngx-quill#300]
The databinding feature isn't working for me. Am I missing something?

My .html
`<quill-editor [sanitize]="true" [style]="{height: '250px'}" [(ngModel)]="requirement.description"></quill-editor>`

My .ts 
![image](https://user-images.githubusercontent.com/23512680/49532007-5afd4580-f89a-11e8-932a-7aee5b7d26d4.png)

My AppModule
![image](https://user-images.githubusercontent.com/23512680/49532148-a57ec200-f89a-11e8-87c9-0ee6a6a3a1fb.png)

**Comment by KillerCodeMonkey** [comment]
what does not work?

check out my demo repos or this https://ngx-quill-dirtiness-demo-ephxwx.stackblitz.io/ there you see the value of the model/formControl after a change ;).

I do not see what the real problem is? Does the initial value is not correctly set, or you changes are not represented on requirements.description.

And which version do you use :)

**Comment by TauanMatos** [comment]
> I do not see what the real problem is? Does the initial value is not correctly set, or you changes are not represented on requirements.description

Both. The initial value is not set and my changes ar note represented on requirements.description.

I'm on version
`"ngx-quill": "^4.3.2"
"quill": "^1.3.6"`

**Comment by KillerCodeMonkey** [comment]
But if i think about it --> you are initialising the editor component before the model is defined.
So you load the page --> ngModel is undefined, because you are loading your data afterwards.

requirements is undefined and if it is loaded later you are creating a new reference. So your model never changes ;)

**Comment by TauanMatos** [comment]
I appreciate your help. Thanks.

**Comment by TauanMatos** [comment]
A possible solution would be not render the editor when the page is loaded?
There are other fields on the page and they are working fine even though when the page is loaded and the ngModel is undefined.

**Comment by KillerCodeMonkey** [comment]
it was only a guess :D. never tried it.

But as you can see it is working in my examples.
I updated https://ngx-quill-dirtiness-demo-ephxwx.stackblitz.io/ to be an async example --> checkout JS console - you get an error in the console, that the model is not defined - but it is working afterwards.

**Comment by TauanMatos** [comment]
And there is a *ngIf, so the component with the editor is rendered after the ngModel requirement is defined.

**Comment by TauanMatos** [comment]
> it was only a guess :D. never tried it.
> 
> But as you can see it is working in my examples.
> I updated https://ngx-quill-dirtiness-demo-ephxwx.stackblitz.io/ to be an async example --> checkout JS console - you get an error in the console, that the model is not defined - but it is working afterwards.

Can I see the code of this example?

**Comment by KillerCodeMonkey** [comment]
sure

https://stackblitz.com/edit/ngx-quill-dirtiness-demo-ephxwx

you can even checkout my example repos linked in the readme. there are many ngModel examples.
And i think your code looks good.

But maybe try the latest ngx-quill version.

**Comment by TauanMatos** [comment]
Ok, I'm going to update ngx-quill version and see what's going to happen.

**Comment by TauanMatos** [comment]
Before the update, I noticed another "problem".
![image](https://user-images.githubusercontent.com/23512680/49534822-54260100-f8a1-11e8-948c-dc5687d9cc39.png)

Can this be one of the causes?

**Comment by KillerCodeMonkey** [comment]
never had this one.
What build process do you use.

plain Webpack, angular cli?

**Comment by TauanMatos** [comment]
I'm using AspNet Boilerplate with Angular. I think it used Webpack but I'm not sure. Where can I look to be sure?

**Comment by KillerCodeMonkey** [comment]
öhhh i do not know :)

But check if you have installed `@angular/common`.
I released v4.4.2 for some minutes, where i added it as peerDependency.
So if you run `npm install` or `yarn install` you should get a warning, that `@angular/common` is not found as peerDependency

**Comment by TauanMatos** [comment]
### Update

I already had installed @angular/common but the error persist.
![image](https://user-images.githubusercontent.com/23512680/49536934-6ce4e580-f8a6-11e8-8c4c-8aafb8ab6399.png)

It looks like that when we use the directive [(ngModel)], your tag needs to have the "name" attribute. After I put this attribute, the data binding started to work.

**Comment by TauanMatos** [comment]
> @TauanMatos is your quill-editor wrapped in a form tag with ngForm attribute?

Yes.

> Then you need a name attribute for each input! But this is an angular restriction :)
Exactly.

Rookie mistake. Sorry for your time.

**Comment by KillerCodeMonkey** [comment]
no probs - i found a little "issue" with the missing peerDependency ;)
