### ISSUE TITLE
Setting initial value for formControl triggers strange validation errors

### ISSUE THREAD

**Issue by maciej-sielski** [KillerCodeMonkey/ngx-quill#823]
Version:
"ngx-quill": "^8.1.0",
"quill": "^1.3.7",

Demo: https://angular-ngx-quill-ms.stackblitz.io

I have a simple form with two formControls: a standard input and quill-editor. Both controls have initial values and some validation. Quill editor should check if initial value complies to validation rules, but it does not or at least it generates strange results.
Please check hero-form.component.ts file on the demo, lines 26-30. What should be the correct initial value for blank document (in json format)?

Please also note, that on some occasions initial error contains "required" instead of "requiredError". Additionally if you set an initial value that is not empty, it doesn't check the length validators.

When you change value via UI everything goes back to normal.

**Comment by KillerCodeMonkey** [comment]
hey thanks for informing me about that.

this can happen, because quilljs is initialised in OnInit and the quill editor is not present for the first validation and so nothing gets validated.

As workaround, you could set your initial value after the `onEditorCreated` output gets called. but then you have to mark your formcontrol als pristine, becaue it will be mark it as `dirty`.

I will try to fix it by calling `changeDetectionRef.markForCheck()`. after the initial content is set.

**Comment by KillerCodeMonkey** [comment]
should be fixed in 8.1.1

i also added a validation example for formcontrols to the example repo:
https://killercodemonkey.github.io/ngx-quill-example/

Section `NgModel/FormControl + Validation`

**Comment by maciej-sielski** [comment]
@KillerCodeMonkey I'm sorry, but that doesn't fix issue with "required" error code. Please check my stackblitz again [https://angular-ngx-quill-ms.stackblitz.io](https://angular-ngx-quill-ms.stackblitz.io)

**Comment by KillerCodeMonkey** [comment]
Default required handling would just check the model/control length, but in quill you need to check the real content of the editor. so the control/model is not empty, but the result in quilljs is. To not clashing with the default required error handling there is the custom one.

Like you have for max and minLength custom errors.

So in general if your json format ist empty quill converts it to a respresentation and i use quill api to get the text-representation of it and validate against it.

Could you share the edit view of your stackblitz?

**Comment by maciej-sielski** [comment]
I understand. But if quill interprets value as empty, then my form control should have _errors_ object with "requiredError" instead of "required", right?

LInk to editor (project is public): https://stackblitz.com/edit/angular-ngx-quill-ms

**Comment by KillerCodeMonkey** [comment]
sure, thatswhy i am asking to check our code in the stackblitz an maybe get an idea whats happening.

maybe i have to rename my required prop to something else. because the native required is clashing with my handling

**Comment by KillerCodeMonkey** [comment]
strange thing.. i am doing the same stuff in my demo repo
https://killercodemonkey.github.io/ngx-quill-example/

https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/model-validation/model-validation.component.html#L11

https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/model-validation/model-validation.component.ts#L13

and it validates when loading the live demo:
https://killercodemonkey.github.io/ngx-quill-example/

the control is validated, marked as invalid, pristine and untouched 🤔

**Comment by KillerCodeMonkey** [comment]
there could be something happen because i changed change detection to OnPush. i switched back to onPush. but 8.1.3 is not available on the fly by stackblitz. so i think we have to wait to test again 🤷‍♂️

**Comment by KillerCodeMonkey** [comment]
seems like your stackblitz is using onPush strategy and is not recognizing the changes.

if you remove it validation works also on init

**Comment by maciej-sielski** [comment]
every other component that implements form control don't need manual change detection triggering. I understand that this needs time to fix and I will implement a hack for now. Either way issue remains imo.

**Comment by KillerCodeMonkey** [comment]
Yeah but quilljs is plain Javascript and some Things (AS of Performance
reasons) are running Out of angular Zone.

And additional to that. I can only init The quill Editor after View init.
But quill Editor ist needed for correct validation.

Initial validation is running before quill Editor is available. So i am
triggering The validation manually after The Editor is created.

So i think there is nothing more i can do :).

And in general when using onpush strategy and formcontrols there are many
Strange Things in angular AS Well.

Many people say that you should subscribe to Control value Changes and
Trigger Change detection manually.

Keep in mind. ChangeDetection only rerenders on DomEvents you are listening
and on Input changes. ;-)

maciej-sielski <notifications@github.com> schrieb am Fr., 27. März 2020,
17:59:
